"""Initial migration.

Revision ID: 6e8d50df1ea2
Revises: 
Create Date: 2024-12-10 10:18:44.336030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8d50df1ea2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compras',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('purchase_direction', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_compra')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compras')
    # ### end Alembic commands ###
